[package]
name = "yew_router"
version = "0.1.0"
authors = ["Henry Zimmerman <zimhen7@gmail.com>"]
edition = "2018"
license = "MIT"


[features]
default = ["core", "unit_alias"]

core = ["router", "components"]

unit_alias = []

router = ["agent"]
components = ["agent" ]

agent = []


[dependencies]
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
yew = "0.9.0"
stdweb = "0.4"

yew_router_route_parser = {path = "crates/yew_router_route_parser"}
yew_router_macro = {path = "crates/yew_router_macro"}
nom = {version = "5.0.0"}
proc-macro-hack = {version = "0.5.9"}


[workspace]

members = [
    "crates/yew_router_route_parser",
    "crates/yew_router_macro",
    "examples/router_component",
    "examples/guide",
    "examples/switch",
    "examples/minimal"
]

